// User
export const SET_USER = "SET_USER"
export const REMOVE_USER = "REMOVE_USER"
export const LOADING_USER = "LOADING_USER"
export const CHANGE_EMAIL = "CHANGE_EMAIL"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_USERNAME = "CHANGE_USERNAME"
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"

// APP
export const SHOW_MESSAGE = "SHOW_MESSAGE"
export const HIDE_MESSAGE = "HIDE_MESSAGE"
export const SHOW_MODAL = "SHOW_MODAL"
export const HIDE_MODAL = "HIDE_MODAL"

// Favorite
export const SET_FAV_ANIMES = "SET_FAV_ANIMES"
export const SET_FAV_CHARACTERS = "SET_FAV_CHARACTERS"
export const LOADING_FAV_ANIMES = "LOADING_FAV_ANIMES"
export const LOADING_FAV_CHARACTERS = "LOADING_FAV_CHARACTERS"
export const PENDING_FAV_ANIME_STARTED = "PENDING_FAV_ANIME_STARTED"
export const PENDING_FAV_ANIME_FINISHED = "PENDING_FAV_ANIME_FINISHED"
export const PENDING_FAV_CHARACTER_STARTED = "PENDING_FAV_CHARACTER_STARTED"
export const PENDING_FAV_CHARACTER_FINISHED = "PENDING_FAV_CHARACTER_FINISHED"
export const ADD_FAV_ANIME = "ADD_FAV_ANIME"
export const ADD_FAV_CHARACTER = "ADD_FAV_CHARACTER"

// Profile
export const SET_PROFILE = "SET_PROFILE"
export const UPDATE_ABOUT = "UPDATE_ABOUT"
export const LOADING_PROFILE = "LOADING_PROFILE"
export const UPLOAD_AVATAR = "UPLOAD_AVATAR"

// Comment
export const SET_COMMENTS = "SET_COMMENTS"
export const ADD_COMMENT = "ADD_COMMENT"
export const LOADING_COMMENTS = "LOADING_COMMENTS"
export const PENDING_COMMENT = "PENDING_COMMENT"
export const SENDING_COMMENT = "SENDING_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"

// Page
export const REMOVE_CURRENT_PAGE = "REMOVE_CURRENT_PAGE"

export const SET_PAGE_TYPE = "SET_PAGE_TYPE"
export const SET_PAGE_COMMENTS = "SET_PAGE_COMMENTS"
export const LOADING_PAGE_COMMENTS = "LOADING_PAGE_COMMENTS"

// Member
export const SET_MEMBER_DATA = "SET_MEMBER_DATA"
export const LOADING_MEMBER_DATA = "LOADING_MEMBER_DATA"
export const DELETE_MEMBER_DATA = "DELETE_MEMBER_DATA"

// Follow
export const SET_FOLLOWERS = "SET_FOLLOWERS"
export const LOADING_FOLLOWERS = "LOADING_FOLLOWERS"
// export const REMOVE_FOLLOWER = "REMOVE_FOLLOWER"

export const SET_FOLLOWINGS = "SET_FOLLOWINGS"
export const LOADING_FOLLOWINGS = "LOADING_FOLLOWERS"

// Discussions
export const SET_THREAD = "SET_THREAD"
export const LOADING_THREAD = "LOADING_THREAD"

export const SET_POSTS = "SET_POSTS"
export const LOADING_POSTS = "LOADING_POSTS"
